### ISSUE TITLE
Modifier apostrophe in acʼhanor

### ISSUE THREAD

**Issue by Trey314159** [belett/Breton_lexicography#1]
The word _acʼhanor_ has a modifier apostrophe (U+02BC) in it, which should probably be a plain apostrophe (_ac'hanor_) like all the others.

Thanks for the list!

**Comment by belett** [comment]
Done (I hesitated to harmonize everything to ʼ or ’ but indeed the "plain" apostrophe is easier and expected).

Thanks for the review.
